from __future__ import annotations

import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import aiosmtplib

from briefing.config import EmailConfig

logger = logging.getLogger(__name__)


async def send_briefing_email(
    email_config: EmailConfig,
    subject: str,
    html_body: str,
) -> None:
    """Send a briefing email via SMTP."""
    username = email_config.username
    password = email_config.password

    if not username or not password:
        logger.warning("Email credentials not configured — set them in Settings. Skipping email.")
        return

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = email_config.from_address
    msg["To"] = email_config.to_address

    # Plain text fallback
    plain = "Your daily briefing is ready. View it in the dashboard."
    msg.attach(MIMEText(plain, "plain"))

    # HTML version wrapped in minimal email-safe styling
    full_html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 700px; margin: 0 auto; padding: 1rem; color: #333; }}
            .card {{ border: 1px solid #ddd; border-radius: 8px; padding: 1rem; margin-bottom: 0.5rem; display: inline-block; width: 45%; vertical-align: top; margin-right: 2%; }}
            .positive {{ color: #16a34a; }}
            .negative {{ color: #dc2626; }}
            .price {{ font-size: 1.3em; font-weight: bold; }}
            .bias-analysis {{ font-style: italic; border-left: 3px solid #6366f1; padding-left: 0.5rem; margin-top: 0.5rem; }}
            .news-story {{ margin-bottom: 1.5rem; padding: 1rem; background: #f9fafb; border-radius: 8px; }}
            table {{ border-collapse: collapse; width: 100%; }}
            th, td {{ border: 1px solid #ddd; padding: 0.5rem; text-align: left; }}
            th {{ background: #f3f4f6; }}
        </style>
    </head>
    <body>
        <h1>Daily Financial Briefing</h1>
        {html_body}
        <hr>
        <p style="font-size:0.8em;color:#999;">Generated by Daily Briefing</p>
    </body>
    </html>
    """
    msg.attach(MIMEText(full_html, "html"))

    try:
        await aiosmtplib.send(
            msg,
            hostname=email_config.smtp_host,
            port=email_config.smtp_port,
            username=username,
            password=password,
            start_tls=True,
        )
        logger.info("Briefing email sent to %s", email_config.to_address)
    except Exception as e:
        logger.error("Failed to send email: %s", e)
        raise
